# Generated by Django 5.0.1 on 2024-01-07 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_article', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('author_email', models.EmailField(max_length=200)),
                ('paragraph_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank='True', null='True', upload_to='uploads/article_images')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
