# Generated by Django 5.0.1 on 2024-01-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_excerts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
