# Generated by Django 5.0.1 on 2024-01-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_article_article_excerts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_excerts',
            new_name='excerts',
        ),
    ]
