# Generated by Django 5.0.1 on 2024-01-08 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_author_email_article_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='excerts',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='paragraph_description',
            new_name='excerpts',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author_name',
            new_name='name',
        ),
    ]
