# Generated by Django 5.0.1 on 2024-01-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_excerts_article_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title_of_article',
            new_name='title',
        ),
    ]
