# Generated by Django 5.0.1 on 2024-01-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_article_is_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
