# Generated by Django 5.0.1 on 2024-01-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_article_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='email',
            new_name='email_of_corresponding_author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='key_words',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='main_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='excerpts',
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default=False, max_length=220),
        ),
        migrations.AddField(
            model_name='article',
            name='name_of_corresponding_author',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='other_author_names',
            field=models.CharField(default=False, max_length=250),
        ),
        migrations.AddField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Research article', 'Research article'), ('short communication', 'short communication')], max_length=200, null=True),
        ),
    ]
