# Generated by Django 5.0.1 on 2024-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_email_article_email_of_corresponding_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Research article', 'Research article'), ('Short communication', 'Short communication')], max_length=200, null=True),
        ),
    ]
