# Generated by Django 5.0.1 on 2024-01-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_article_type_of_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='abstract', max_length=220),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_of_corresponding_author',
            field=models.CharField(default='name_of_corresponding_author', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='other_author_names',
            field=models.CharField(default='other authors name', max_length=250),
        ),
    ]
