# Generated by Django 5.0.1 on 2024-01-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_article_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Short communication', 'Short communication'), ('Research article', 'Research article')], max_length=200, null=True),
        ),
    ]
