# Generated by Django 5.0.1 on 2024-01-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_article_type_of_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Research article', 'Research article'), ('Short communication', 'Short communication'), ('Review article', 'Review article')], max_length=200, null=True),
        ),
    ]
