# Generated by Django 5.0.1 on 2024-01-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_article_type_of_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name_of_corresponding_author',
            field=models.CharField(default='name of corresponding_author', max_length=200),
        ),
    ]
