# Generated by Django 5.0.1 on 2024-01-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_article_options_alter_article_type_of_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Research article', 'Research article'), ('Short communication', 'Short communication'), ('Review article', 'Review article')], max_length=200, null=True),
        ),
    ]
