# Generated by Django 5.0.1 on 2024-01-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_article_options_alter_article_type_of_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='article',
            name='name_of_corresponding_author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Research article', 'Research article'), ('Review article', 'Review article'), ('Short communication', 'Short communication')], max_length=200, null=True),
        ),
    ]
