# Generated by Django 5.0.1 on 2024-01-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_article_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='other_author_names',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Review article', 'Review article'), ('Short communication', 'Short communication'), ('Research article', 'Research article')], max_length=200, null=True),
        ),
    ]
