# Generated by Django 5.0.1 on 2024-01-22 05:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_article_other_author_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Short communication', 'Short communication'), ('Research article', 'Research article'), ('Review article', 'Review article')], max_length=200, null=True),
        ),
    ]
