# Generated by Django 5.0.1 on 2024-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_article_main_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Short communication', 'Short communication'), ('Review article', 'Review article'), ('Research article', 'Research article')], max_length=200, null=True),
        ),
    ]
