# Generated by Django 5.0.1 on 2024-02-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_article_type_of_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_author',
        ),
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/article_images/pdf_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Review article', 'Review article'), ('Research article', 'Research article'), ('Short communication', 'Short communication')], max_length=200, null=True),
        ),
    ]
