# Generated by Django 5.0.1 on 2024-02-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_article_is_author_article_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Research article', 'Research article'), ('Review article', 'Review article'), ('Short communication', 'Short communication')], max_length=200, null=True),
        ),
    ]
