# Generated by Django 5.0.1 on 2024-02-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_article_pdf_alter_article_type_of_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Short communication', 'Short communication'), ('Review article', 'Review article'), ('Research article', 'Research article')], max_length=200, null=True),
        ),
    ]
