# Generated by Django 5.0.1 on 2024-02-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_article_type_of_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_upload',
            field=models.FileField(blank='True', null='True', upload_to='uploads/article_images/pdf'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Review article', 'Review article'), ('Short communication', 'Short communication'), ('Research article', 'Research article')], max_length=200, null=True),
        ),
    ]
