# Generated by Django 5.0.1 on 2024-02-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_article_type_of_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_of_articles',
            field=models.CharField(blank=True, choices=[('Review article', 'Review article'), ('Short communication', 'Short communication'), ('Case study', 'Case study'), ('Research article', 'Research article')], max_length=200, null=True),
        ),
    ]
